### ISSUE TITLE
Docker build is broken

### ISSUE THREAD

**Issue by pluma** [RnbWd/sinopia-docker#1]
The docker build for 1.0.1 is broken.

See https://registry.hub.docker.com/u/rnbwd/sinopia/builds_history/93140/

**Comment by RnbWd** [comment]
Joyent forked node's docker repo recently and didn't include some build dependencies in node:slim (like git), so I rebuilt it [here](https://registry.hub.docker.com/u/rnbwd/node-io/) for consistency with the original version. It should work now (build finished) using node v0.10.36 and npm 2.6.0.
