### ISSUE TITLE
Paths are wrong

### ISSUE THREAD

**Issue by levino** [RnbWd/sinopia-docker#3]
Suddenly the image takes the config fom `/sinopia/sinopia/config.yaml` before is was `/sinopia/config.yaml`. Some mess up with the latest changes I assume.

**Comment by RnbWd** [comment]
Honestly I've noticed it for almost a month now and I have no idea what's happening - there's inconsistencies between docker and node versions. I've actually seen the app break from minor releases of node, so it's switched between modern / 0.10 whenever I can't get it work in the main branch. 

But -- there's a way to use -v to include your own custom path for config.yaml - or if you've already figured it out somehow - or want to try - the dockerfile is pretty small - it might just need a tiny tweak in how the paths are referenced. i'll probably figure it out this week. I also want to update it to a modern fork that some people are starting to maintain.

**Comment by RnbWd** [comment]
I think my comment for this last commit reflects how I feel about the situation https://github.com/RnbWd/sinopia-docker/commit/3121f8017fb39e8445dadf1e94385c83028674f3

**Comment by RnbWd** [comment]
ahh this line is probably what's wrong with it:

`ADD /config.yaml /sinopa/config.yaml`

should be something like `COPY /config.yaml /config.yaml`

**Comment by RnbWd** [comment]
Anyone good with using volume containers by chance?

**Comment by RnbWd** [comment]
paths moved to /sinopia/registry - and the issue should be fixed
