### ISSUE TITLE
Should :/sinopia/config.yaml be :/sinopia/sinopia/config.yaml

### ISSUE THREAD

**Issue by maxfriedmann** [RnbWd/sinopia-docker#5]
:/sinopia/config.yaml doesn't seem to be used. If I use :/sinopia/sinopia/config.yaml it works as expected, otherwise, no changes in the hosts config.yaml are taken into account.

**Comment by maxfriedmann** [comment]
same for /sinopia/sinopia/storage

actually duplicates #3

**Comment by RnbWd** [comment]
Sorry for the delayed response - My goal this afternoon will be to stablize the library - fix the path issues within the Dockerfile and leverage any features that will be arriving in 0.12 next week.  

But

**Comment by RnbWd** [comment]
WORKDIR was probably in the wrong location, it should be fixed now (hopefully)
